### ISSUE TITLE
Code about the t-SNE visualization section

### ISSUE THREAD

**Issue by Adherer** [thunlp/relation-similarity#1]
Hello, I read the paper you published at the ACL 2019 conference, I am very interested, and found your implementation code through github. When I reproduce your experiment, I found that t-SNE visualization is missing from your code. Because I am very interested in your work, and want to study your work well, if you are convenient, can you send me the code related to t-SNE visualization in your work? My mailbox is adherersun@163.com, I am grateful!

**Comment by chenweize1998** [comment]
Hi there. Implementing the visualization is trivial so you can try yourself. For the relation you want to visualize, you can sample an entity pair from the probability distribution of the relation over all the entity pairs, then concatenate the embedding vectors of head and tail entity. Repeat the procedure several times and store the concatenated vectors in a file, then you can use tensorboardX (if you use Tensorflow, then tensorboard can be directly used) to visualize the distribution. If you still have any problem, you can send me an email for further detail.
