### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by xinyuwang1126** [thunlp/relation-similarity#2]
Hi Weize,
I am trying to replicate the experiment using the given command:
"python train.py --input ./data/wikipedia --output ./checkpoint -ent_pretrain -rel_pretrain"
but I got this error:

""Traceback (most recent call last):
  File "train.py", line 69, in <module>
    model = baseModel(args, info['tot_ent'], info['tot_rel']).cuda()
  File "/Users/Desktop/relation-similarity/models/baseModel.py", line 35, in __init__
    self.eemb.weight = nn.Parameter(torch.FloatTensor(entity_pretrain))
ValueError: expected sequence of length 100 at dim 1 (got 61)""

The .vec files are the same ones in the repo. Is there anything I am missing? I am using python 3.6 and pytorch 1.0.1 .  Thank you!

**Comment by chenweize1998** [comment]
Sorry for the wrong pretrained embedding files. I didn't notice that the pretrained files exceed GitHub's file size limit, so the embedding files uploaded to the repo are incomplete. 

However, it's pretty easy to get the pretrained embedding files. You can simply use [OpenKE](https://github.com/thunlp/OpenKE) to train TransE on the dataset, and use the yielded embedding as the pretrained embedding.

Or if you still think it's somewhat complicated, I will post a download link later.

**Comment by chenweize1998** [comment]
I have uploaded the compressed pretrained embedding file. You have to decompress before using it.
